all:
	reset
	gcc listaC01/01.c -o bins/01.o
	gcc listaC01/02.c -o bins/02.o
	gcc listaC01/03.c -o bins/03.o

	gcc laboratorios_2022/lab01.c -o bins/lab01.o
	gcc laboratorios_2022/lab02.c -o bins/lab02.o
	# gcc laboratorios_2022/lab03.c -o bins/lab03.o
	# gcc laboratorios_2022/lab04.c -o bins/lab04.o
	# gcc laboratorios_2022/lab05.c -o bins/lab05.o
	
	# lab 2024
	gcc lab_24/lab03.c lab_24/lab03_func.c -o bins/lab03.o