# evitando a destruicao e criacao de compilacoes desnecessarias

# evite ter que destruir e compilar todos os seus arquivos do programa

# compile apenas aqueles que foram alterados ou que ainda não existem

$(PASTA_VARIAVEL)/arquivo_compilado.o: $(PASTA_VARIAVEL)/arquivo_fonte.c $(INCLUDE)/arquivo_cabecalho.h
	
	execute algo como por exemplo a compilacao dos arquivos da 
		$(PASTA_VARIAVEL)/arquivo_compilado.o 
	
	caso 
		$(PASTA_VARIAVEL)/arquivo_fonte.c 
	
	ou 
		$(INCLUDE)/arquivo_cabecalho.h 
	
	tenham sido alterados

	ou se o 
		$(PASTA_VARIAVEL)/arquivo_compilado.o não existir






# agora para chama-lo no all e alguma diretiva especifica passe o:
$(PASTA_VARIAVEL)/arquivo_compilado.o