# para criar arquivos makefile use " Makefile " sempre coloque M

# semre use tab para definir o corpo da diretiva

# all == diretiva padrao que todo Makefile tem
all:
	echo "HelloWorld"


# crie suas proprias diretivas
diretiva_personalizada:
	echo "essa diretiva e personalizada"